<a href="https://colab.research.google.com/github/kevinvantus/tensorflow-python-tutorials/blob/tensors/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())
print(rank_1_tensor[0].numpy())
print(rank_1_tensor[1].numpy())
print(rank_1_tensor[2].numpy())

[ 0  1  1  2  3  5  8 13 21 34]
0
1
1


In [ ]:
rank_2_tensor = tf.constant(
    [
        [1., 2.],
        [3., 4.],
        [5., 6.]
    ]
)
print(rank_2_tensor.shape)
print(tf.reshape(rank_2_tensor, [-1]))
print(tf.reshape(rank_2_tensor, [2, 3]))
print(tf.reshape(rank_2_tensor, [1, 6]))
print(tf.reshape(rank_2_tensor, [6, 1]))

(3, 2)
tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor([[1. 2. 3. 4. 5. 6.]], shape=(1, 6), dtype=float32)
tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]], shape=(6, 1), dtype=float32)


In [ ]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_int32_tensor = tf.cast(the_f64_tensor, tf.int32)
print(the_int32_tensor.numpy())

[2 3 4]
